### ISSUE TITLE
Nivelar la CNC

### ISSUE THREAD

**Issue by jdpalermo** [GrupoPalermo/PEC_Panama#40]
Se requieren realizar los siguientes trabajos
- [ ] Nivelar fisicamente la CNC
- [ ] Cablibrar y/ Nivelar la cama de corte
- [ ] Calibrar la Z 
- [ ] Instalar la aspiradora
